### ISSUE TITLE
got   the following arguments are required: --style-dataset

### ISSUE THREAD

**Issue by Wisgon** [WellyZhang/MetaStyle#1]
when I try to use fast train:
$python src/main.py train --content-dataset test2017 --style-image images\style\sketch.png --model MetaStyle.pth --cuda 1
 ,i got the error:
" following arguments are required: --style-dataset"
please tell me what to do

**Comment by WellyZhang** [comment]
Please note that to use fast train, run

python src/main.py fast ...

**Comment by Wisgon** [comment]
Thanks, I ran it successfully, but your instruction of fast train in README.md is :
`python src/main.py train --content-dataset <path-to-your-content-dataset> --style-image <path-to-your-style-image> --model <path-to-your-trained-model> --cuda 1`

And BTW, I have to run the command below to ran the fast train successfully:
`$mkdir -p experiments/save`
`$cd experiments/save`
`$touch sketch.pth`

Then I run fast train successfully.

Anyway, thank you very much for replying!
