### ISSUE TITLE
Related work on style transfer from Heidelberg University

### ISSUE THREAD

**Issue by asanakoy** [WellyZhang/MetaStyle#2]
Hi,

Thanks for an amazing work!
You may also be interested in the work of our group on style transfer. 
Here are some of our recent papers:

A Style-Aware Content Loss for Real-time HD Style Transfer (ECCV19, Oral)
https://compvis.github.io/adaptive-style-transfer/ 

A Content Transformation Block for Image Style Transfer (CVPR19)
https://compvis.github.io/content-targeted-style-transfer/  

Content and Style Disentanglement for Artistic Style Transfer (ICCV19)
https://github.com/CompVis/content-style-disentangled-ST 

We would highly appreciate if cite our works in your paper.

Best,
Artsiom

**Comment by WellyZhang** [comment]
Hi Artsiom,

Thanks for providing some related papers. We will cite them when we have related work to submit in the future. And it is definitely welcome when you do and cite ours.
