### ISSUE TITLE
Why only 'fast_weights(in_weights)' are updated during meta-learning stage?

### ISSUE THREAD

**Issue by raidria** [WellyZhang/MetaStyle#4]
I wonder why only the 'fast_weights(in_weights)' are updated excluding conv&deconv layers in inner loop. (line 166 in main.py)

Is it make the learning faster or something?

**Comment by WellyZhang** [comment]
It's basically for efficiency.

**Comment by sunshower76** [comment]
@WellyZhang I have same question. Is there any reference which explains this tricks?  Could you give brief or little explanation it? Thanks :)
